# Copyright 2018-2019 Peter Williams
# Licensed under the MIT License

language: rust

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
    - os: osx
      osx_image: xcode10.2
      rust: stable
  allow_failures:
    - rust: nightly

# Don't build branches besides master -- note that PR's still get built! This
# prevents PRs being built twice in the standard workflow.
branches:
  only:
    - master

before_script:
  - rustup component add rustfmt

# Note: `cc` version 1.0.42 somehow made it so that Travis started thinking
# the build had stalled; I can fix it with --jobs=4. I think it has to do with
# a change for `cc` to start using the Cargo jobserver, but I can't reproduce
# locally and don't feel like I understand what the actual issue is.
script:
  - |
    cargo fmt --all -- --check &&
    cargo build --verbose --jobs=4 &&
    cargo test --all
