# Copyright 2017-2020 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_core"
version = "0.0.0-dev.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Core types and traits for Rubbl, a Rust package for astrophysics.
"""

[dependencies]
anyhow = "^1.0"
byteorder = "^1.4"
clap = "^2.33"
ndarray = "^0.15"
num-complex = "^0.4"
termcolor = "^1.1"
thiserror = "^1.0"
