# Copyright 2017-2019 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_casatables"
version = "0.1.1"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"
homepage = "https://github.com/pkgw/rubbl"
repository = "https://github.com/pkgw/rubbl"
description = """
Interfacing to the CASA table format within the Rubbl framework.
"""

[dependencies]
byteorder = "^1.3"
clap = "^2.33"
failure = "^0.1"
failure_derive = "^0.1"
itertools = "^0.8"
ndarray = "^0.12"
nom = "^4.2"
num-traits = "^0.2"
pbr = "^1.0"
rubbl_casatables_impl = { version = "0.2.311", path = "../casatables_impl" }
rubbl_core = { version = "0.1.2", path = "../core" }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
