# Copyright 2018-2019 Peter Williams <peter@newton.cx> and collaborators
# Licensed under the MIT License.

[package]
name = "rubbl_fits"
version = "0.1.0"
authors = ["Peter Williams <peter@newton.cx>"]
license = "MIT"

[dependencies]
byteorder = "^1.3"
clap = "^2.33"
failure = "^0.1"
failure_derive = "^0.1"
rubbl_core = { path = "../core", version = "0.1.2" }
rubbl_visdata = { path = "../visdata", version = "0.1.0" }
